### PR TITLE
Script to clip an existing geojson based in an OSM relation ID

### PR DESCRIPTION
**Pull request by jsanz**
This script is inteded to work after the first step script to remove from that step square layer those features that are not contained by the polygon defined by the relation identifier in OSM for the city.

The script accepts just a city name and an OSM identifier.

### CODE REVIEW

**Comment by jsanz** [comment]
@jessisena this is still a work in progress but you can already test the script. I want also to update the documentation. Let me know if apart from that there's anything else I should take care of.

**Comment by jessisena** [comment]
> @jessisena this is still a work in progress but you can already test the script. I want also to update the documentation. Let me know if apart from that there's anything else I should take care of.

@jsanz it looks good 👍 But just tell me when is completely finished, because it will imply some changes in the current process (in order to be able to use it).

Thanks!

**Comment by jsanz** [comment]
@jessisena before review I want to explore the idea of integrating this into the first step logic so instead of first clip an area and then afterward a polygon, just pass one or the other option to the Tile Reduce logic. I'll try to find some time this weekend :muscle:

**Comment by jessisena** [comment]
As for now the functionality is completely isolated, no problem about merging it in the master branch.

**Pull request merged**
